# Generated by Django 4.0.5 on 2022-06-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('app_name', models.CharField(max_length=200)),
                ('work_name', models.CharField(max_length=100)),
                ('work_descp', models.TextField(max_length=700)),
            ],
        ),
    ]
