# Generated by Django 4.0.5 on 2022-06-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
