# Generated by Django 4.0.5 on 2022-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_alter_worker_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('app_name', models.CharField(max_length=200)),
                ('work_name', models.CharField(max_length=100)),
                ('work_descp', models.TextField(max_length=700)),
                ('work_time', models.TimeField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
