# Generated by Django 4.0.5 on 2022-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0006_sworker_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField(max_length=200)),
                ('app_code', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='work_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
