# Generated by Django 4.0.5 on 2022-06-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0007_app_models_work_type_delete_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='sworker',
            name='work_status',
            field=models.BooleanField(default=False),
        ),
    ]
