# Generated by Django 4.0.5 on 2022-06-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0008_sworker_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sworker',
            name='work_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
