# Generated by Django 4.0.5 on 2022-06-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0009_alter_sworker_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sworker',
            name='work_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
