# Generated by Django 4.0.5 on 2022-06-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0010_alter_sworker_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sworker',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
