# Generated by Django 4.0.5 on 2022-06-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0012_alter_sworker_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sworker',
            name='permission_status',
            field=models.BooleanField(default=False),
        ),
    ]
