# Generated by Django 4.0.5 on 2022-06-15 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0013_sworker_permission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_models',
            name='app_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.sworker'),
        ),
        migrations.AlterField(
            model_name='sworker',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work_type',
            name='app_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.app_models'),
        ),
    ]
