# Generated by Django 4.0.5 on 2022-06-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0014_alter_app_models_app_name_alter_sworker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_models',
            name='app_name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sworker',
            name='app_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.app_models'),
        ),
    ]
