# Generated by Django 4.0.5 on 2022-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0015_alter_app_models_app_name_alter_sworker_app_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sworker',
            name='work_time',
        ),
        migrations.AlterField(
            model_name='sworker',
            name='time',
            field=models.TextField(max_length=100),
        ),
    ]
