# Generated by Django 4.0.5 on 2022-06-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0016_remove_sworker_work_time_alter_sworker_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sworker',
            name='work_time',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sworker',
            name='time',
            field=models.TextField(max_length=200),
        ),
    ]
